"""empty message

Revision ID: 304f141fc956
Revises: 
Create Date: 2018-12-06 01:54:03.788206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '304f141fc956'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    # ### end Alembic commands ###
