"""empty message

Revision ID: 87824343f07b
Revises: 304f141fc956
Create Date: 2018-12-22 01:15:53.841001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87824343f07b'
down_revision = '304f141fc956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'title')
    # ### end Alembic commands ###
